### ISSUE TITLE
Different rendering quality between MetalSplatter and original C++ viewer

### ISSUE THREAD

**Issue by gcccccccccccc12345** [scier/MetalSplatter#11]
![微信图片_20240401231118](https://github.com/scier/MetalSplatter/assets/92901141/d34eb41b-818c-4ad1-9d30-796435ab4c60)
![微信图片_20240401231110](https://github.com/scier/MetalSplatter/assets/92901141/dc00ff54-26d6-43a5-9142-0ceaeb489203)
I use the same Lego.ply and use SIBR C++ viewer and MetalSplatter, and I got different results when I zoom in, the metalsplatter may have more artifacts, do you have any idea about it ?

**Comment by scier** [comment]
There are a number of differences in the training-time renderer and real-time quad-based renderers, e.g. spherical harmonics (which can be added to MetalSplatter, see #10), and per-pixel depth (which cannot easily be added). I think this issue will be gradually improved from both directions -- adding functionality to real-time renderers like MetalSplatter (e.g. #10), and using a training-time renderer that more accurately captures these limitations and hence considers them in the optimization. But ultimately, the goals of the two simply vary; for instance, real-time renderers will always have a performance pressure that the training-time renderer simply does not, and so the results will likely always slightly vary.

I'm going to close this as it's too broad, but feel free to open issues for more specific enhancements you'd like to see to help improve this situation.
