### ISSUE TITLE
"Shakiness in Rendered Image When Moving Head in VisionPro: Is It Dropping Frames?"

### ISSUE THREAD

**Issue by zxwzxw** [scier/MetalSplatter#14]
"Why does the rendered image in VisionPro appear shaky when moving the head to look around? Could it be dropping frames?"

**Comment by scier** [comment]
Two reasons. First is that, you are correct, most scenes do not render at the 90fps x 2 required for full framerate on the Vision Pro. Second reason is that the Vision Pro extrapolates frames based on user motion and depth to fill in the missing frames, which uses a warping algorithm; the combination of that algorithm not being able to perfectly extrapolate, plus very approximate depth data, results in a "wobbly" effect in various regions. The bigger and slower to render the scene is -- the wobblier it appears.

See also: https://github.com/scier/MetalSplatter/issues/12
