### ISSUE TITLE
use both hands for moving, rotating, and scaling splat scenes?

### ISSUE THREAD

**Issue by zxwzxw** [scier/MetalSplatter#16]
I want to use both hands for moving, rotating, and scaling splat scenes. Currently, I only know how to move scenes using a pinch gesture with one hand. Is my approach correct? I'm using inputDevicePose in layerRenderer.onSpatialEvent to calculate the position.

![微信截图_20240507224625](https://github.com/scier/MetalSplatter/assets/8348226/6af46e86-c73e-4137-b050-8f197ef6f55d)
![微信截图_20240507224746](https://github.com/scier/MetalSplatter/assets/8348226/de545e5c-3056-4843-b7ae-741d823e3b58)

[splatting_testzjhApp.txt](https://github.com/scier/MetalSplatter/files/15237258/splatting_testzjhApp.txt)
[VisionSceneRenderer.txt](https://github.com/scier/MetalSplatter/files/15237259/VisionSceneRenderer.txt)

**Comment by scier** [comment]
You're using the correct data, the key is just that you're using each event independently, and one hand is overwriting the other hand; you need to use all of the events sent to onSpatialEvent in concert in order to use multi-hand gestures.
