### ISSUE TITLE
Error loading model: Unexpected file contents for a splat PLY: Unexpected type for property "x"

### ISSUE THREAD

**Issue by vescreative** [scier/MetalSplatter#17]
I have tried building this in both VisionOS Simulator and MacOS, and any model from Luma results in Error loading model: Unexpected file contents for a splat PLY: Unexpected type for property "x"

**Comment by scier** [comment]
Are you using the latest commit on main? If not, please try this, as there've been several fixes that should help load Luma models. Also, are you sure you downloaded the "Splat" file from Luma (which, yes, is a PLY), not a point cloud PLY? If you are using the Splat file and the latest commit, could you attach the header? I just tried with a newly-captured luma file and didn't have any problem.
