### ISSUE TITLE
Did official app diverged from this implementation?

### ISSUE THREAD

**Issue by s1ddok** [scier/MetalSplatter#19]
Hey! Thank you open sourcing this! 

However I'm observing that official app provides much smoother experience. Am I correct to assume that it is not true that it is based off this library? If it is though, is it some post-release AppStore magic from Apple?

**Comment by scier** [comment]
The app does indeed use this library (the library is actually slightly newer); I’d suggest making sure you are running in Release mode, and without the debugger attached — that is, try exiting Xcode and launching the app from the Home Screen. If you’re still seeing a performance difference, reopen and let’s see if we can get to the bottom of it.
