### ISSUE TITLE
PLYIO.PLYHeader.ASCIIDecodeError.headerUnknownKeyword("obj_info")

### ISSUE THREAD

**Issue by vade** [scier/MetalSplatter#22]
Thanks again for this project. Im noticing some minor file parsing hiccups in for files in the wild, specifically off of SketchFab  made with some other tools.

Seems like some Splat files have some additional fields that PLYIO or doesnt handle correctly. In the wild, ive seen a few hiccups.

`PLYIO.PLYHeader.ASCIIDecodeError.headerUnknownKeyword("obj_info")`

and if I manually remove that line from the PLY file:

`obj_info Generated by CloudCompare!`

 I get :

`SplatIO.SplatPLYSceneReader.Error.unsupportedFileContents(Optional("No property named \"scale_0\" found"))`

**Comment by vade** [comment]
Ah, these might just be ply files that dont have the correct Gaussian Splat metadata required but are badly formed. Interesting.

**Comment by vade** [comment]
FWIW I added the `obj_info` header parsing! I hope you dont mind the PRs! :)

**Comment by scier** [comment]
Don't mind at all -- I very much appreciate it!

**Comment by scier** [comment]
Fixed by #23
