### ISSUE TITLE
Battery drain issue on Apple Vision Pro

### ISSUE THREAD

**Issue by kevinmore** [scier/MetalSplatter#30]
Hi,

I’m relatively new to 3DGS and Metal. When exploring the sample app and also the official App Store app, I noticed the battery drained very quickly when viewing models. 

Is this a known issue or not an issue at all?

**Comment by scier** [comment]
Viewing splats is, well, very demanding on both GPU and CPU. The library lets apps choose whether to throttle, but I expect most would not, as long as the camera's moving (and on Vision Pro, the camera's always moving). For instance, the MetalSplatter app store app doesn't attempt to throttle performance to reduce power; as-is, it's usually unable to achieve the a full 90fps, so the GPU and CPU are running full-out. 

This isn't really any different from most graphically demanding games (e.g. AAA titles), but the assumption is that most people won't be spending long enough viewing splats to be concerned.

So yeah it's an issue in general, but it's not a bug, simply a tradeoff an app needs to make.
