### ISSUE TITLE
Low frame rate viewing .splat models on Apple Vision Pro

### ISSUE THREAD

**Issue by kevinmore** [scier/MetalSplatter#31]
Hi,

As mentioned in title, when viewing .splat models, the frame rate is much slower than .ply models. Sometimes it even freezes. This happens in both the sample app(release mode) and the official App Store app.

What caused the low performance for .splat files?

**Comment by scier** [comment]
I haven't observed this. Are the PLY and .splat you're using identical in terms of their contents? There *shouldn't* be a frame rate difference if so; once the file's loaded, the data being rendered should be the same regardless of source format.

That said, if you're observing this with a matching pair of files, is there anywhere I can access these files to try to reproduce?

And, how are you measuring framerate -- is it just an observation (which is totally valid), or are you doing some sort of measurement or performance profiling?

**Comment by kevinmore** [comment]
I think you're right, as I tried more models today, comparing identical ones in ply and splat format, the rendering results are identical.

But could you try this classic bicycle scene?  https://huggingface.co/cakewalk/splat-data/resolve/main/bicycle.splat

It's very slow on Vision Pro. Is it simply because it's too large?

**Comment by scier** [comment]
Yes, that one's ~6.1m splats. I get about 7-10fps viewing it. Though I'd suggest trying with the current HEAD (as of a day or so ago) if you haven't, it makes it 'feel' much smoother with improved depth for frame reprojection.
