### ISSUE TITLE
Question about color format

### ISSUE THREAD

**Issue by kevinmore** [scier/MetalSplatter#32]
Hi,

I noticed in the sample app, the color format is set to `.bgra8Unorm_srgb`. Does it support HDR? Is there a particular reason behind this choice?

According to this Apple's [documentation](https://developer.apple.com/documentation/compositorservices/drawing_fully_immersive_content_using_metal#4198157),  `.rgba16Float` is used to render HDR content.

**Comment by scier** [comment]
Unfortunately 3DGS itself (at least the original basic representation) does not support HDR. There have been a number of papers on adding HDR support to 3DGS, and I can't wait to see the results as they enter the mainstream, but they'll need explicit changes to the renderer (and the defacto PLY schema, as the color representation in the current common schema can only support color value in the range 0..1). Once it's possible to represent and render HDR, then you're quite correct that we'll need to use a different color format to store the results.
