### ISSUE TITLE
Showcase contribution?

### ISSUE THREAD

**Issue by kevinmore** [scier/MetalSplatter#37]
Hi,

Thanks for this amazing project. I’ve integrated it into my app on visionOS App Store.

I’m wondering if you would accept me adding a new section to the readme called “Showcase” so that people can put their apps into it?

**Comment by scier** [comment]
Thank you @kevinmore , I'm glad you were able to put it to good use -- I'd love to see your app; do you have a link?

The Showcase is a good idea (perhaps we could replace the "MetalSplatter Model Viewer" section in README.md, and have the "official app" as an entry in that list). I'll take a look, or certainly feel free to submit a PR.

**Comment by kevinmore** [comment]
@scier Please take a look at https://apps.apple.com/app/id6475262918
