### ISSUE TITLE
Support reading ".splat" files created by Kevin Kwok's antimatter15 viewer

### ISSUE THREAD

**Issue by yosun** [scier/MetalSplatter#5]
why does this only accept ply files? ideally we could support more than just vertex colors?

**Comment by scier** [comment]
What format would you like support for? And, what do you mean by “more than just vertex colors” — are you talking about spherical harmonics?

**Comment by catid** [comment]
Yeah SH would be nice

**Comment by scier** [comment]
I've split Spherical Harmonics out to issue #10. Nobody said what formats you'd like support for; the top two I've seen around are Kevin Kwok's antimatter15 "splat" files, and PlayCanvas's "Compressed PLY" which is already requested in issue #7, so I'll go ahead and repurpose this issue for splat files in particular.

**Comment by scier** [comment]
Implemented by commit 32c1669
