### ISSUE TITLE
Why there is difference color between vision pro app with ios app？

### ISSUE THREAD

**Issue by moqiyinlun** [scier/MetalSplatter#8]
Since I directly return float4(sRGBToLinear(0.4521f),sRGBToLinear(0.131412f),sRGBToLinear(0.63231f),1.0f); in vision pro and ios app, and I set the pixelcolorformat the same with bgraunit8norm, but I get different result?
![20240328-005903](https://github.com/scier/MetalSplatter/assets/95729348/97394a5f-5873-43ca-b56d-a1bf0cd15c97)

**Comment by moqiyinlun** [comment]
Is it the reason why there is a different rendering result between vision pro one with IOS app(https://github.com/laanlabs/metal-splats)

**Comment by scier** [comment]
Hard to compare these two -- two totally different codebases, and with simulators in the mix (and it looks like an app being run in compatibility mode?) there could be all kinds of differences through the pipeline.

Or are you running the MetalSplatter sample app on both iOS and visionOS and seeing different results?

**Comment by scier** [comment]
Closing for lack of information; please reopen if you can verify that the same app codebase is resulting in different colors on different platforms, and we can take it from there.
